# These substitutions allow the end user to override certain values
substitutions:
  name: "germination-chamber"
  friendly_name: "Germination Chamber"
  comment: A box for germinating plants

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  comment: "${comment}"
  # Automatically add the mac address to the name
  # so you can use a single firmware for all devices
  name_add_mac_suffix: true

  # This will allow for (future) project identification,
  # configuration and updates.
  project:
    name: "cblumer.plant-minder"
    version: "0.0.4-dev"

# This should point to the public location of this yaml file.
dashboard_import:
  package_import_url: github://CurtisBlumer/esphome-plant-minder/germination-chamber-esp8266.yaml@main
  import_full_config: true

packages:
  status_led: !include
    file: common/base-esp8266.yaml
    vars:
      esp8266_board: d1_mini
      status_led_pin: D3
  
  intake_fan: !include
    file: common/fan/fan-pwm.yaml
    vars:
      pwm_platform: esp8266_pwm
      pin: D0
      id: intake_fan
      name: Intake Fan
