# https://esphome.io/guides/configuration-types#packages-as-templates
defaults:
  # Output variables
  # pwm_platform: ""
  # id: ""
  # pin: ""
  pin_inverted: "false"
  pwm_frequency: "25000"
  pwm_min_power: "0.2"
  pwm_max_power: "1"
  # Fan variables
  restore_mode: "ALWAYS_OFF"
  # name: ""
  speed_count: "10"
  high_preset_name: "High"
  high_preset_speed: "10"
  medium_preset_name: "Medium"
  medium_preset_speed: "7"
  low_preset_name: "Low"
  low_preset_speed: "4"
  quiet_preset_name: "Quiet"
  quiet_preset_speed: "1"
  off_preset_name: "Off"

  

  start_threshold: "20.0"
  stall_threshold: "0.0"
  ramp_up_speed: "100"
  ramp_up_delay: "75ms"

# https://esphome.io/components/esphome
esphome:
  # https://esphome.io/components/esphome#on-boot
  on_boot:
    priority: -100
    then:
      - logger.log:
          format: "Setting ${name} Frequency to %-.0f"
          args:
            - id(${id}_frequency).state
          level: INFO
          tag: ${id}
      - output.esp8266_pwm.set_frequency:
          id: ${id}_output
          frequency: !lambda return id(${id}_frequency).state;

packages:
  fan-base: !include
    file: fan-base.yaml
    vars:
      id: ${id}

# https://esphome.io/guides/automations#global-variables
globals:
  - id: ${id}_startup_speed
    type: int
    restore_value: no

# https://esphome.io/components/number
number:
  - platform: template
    name: "${name} Frequency"
    id: ${id}_frequency
    disabled_by_default: true
    entity_category: config
    unit_of_measurement: Hz
    device_class: frequency
    min_value: 100
    max_value: 40000
    step: 1
    set_action:
      - output.${pwm_platform}.set_frequency:
          id: ${id}_output
          frequency: !lambda return x;
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: ${pwm_frequency}

  - platform: template
    name: "${name} Start Threshold"
    id: ${id}_start_threshold
    disabled_by_default: true
    entity_category: config
    unit_of_measurement: "%"
    device_class: ""
    min_value: 0
    max_value: ${speed_count}
    step: 1
    update_interval: never
    optimistic: true
    restore_value: true
    initial_value: ${speed_count}

# https://esphome.io/components/output
output:
    # https://esphome.io/components/output/ledc
    # https://esphome.io/components/output/esp8266_pwm
    # https://esphome.io/components/output/libretiny_pwm
  - platform: ${pwm_platform}
    id: ${id}_output
    pin:
        number: ${pin}
        inverted: ${pin_inverted}
    frequency: ${pwm_frequency}
    min_power: ${pwm_min_power}
    max_power: ${pwm_max_power}
    zero_means_zero: true

# https://esphome.io/components/fan
fan:
  # https://esphome.io/components/fan/speed
  - platform: speed
    output: ${id}_output
    name: ${name}
    id: ${id}
    speed_count: ${speed_count}
    restore_mode: ${restore_mode}
    #icon: ${icon}
    preset_modes:
      - ${high_preset_name}
      - ${medium_preset_name}
      - ${low_preset_name}
      - ${quiet_preset_name}
      - ${off_preset_name}
    on_turn_on:
      - logger.log:
          format: ${name} turned on
          level: INFO
          tag: ${id}
    on_turn_off:
      - logger.log:
          format: ${name} turned off
          level: INFO
          tag: ${id}
    on_speed_set:
      - logger.log:
          format: ${name} speed was changed to %d
          args:
            - x
          level: INFO
          tag: ${id}
    on_preset_set:
      - if:
          condition:
            lambda: return x != "";
          then:
            - logger.log:
                format: ${name} preset mode was changed to "%s"
                args:
                  - x.c_str()
                level: INFO
                tag: ${id}
      - if:
          condition:
            lambda: return x == "${quiet_preset_name}";
          then:
            - script.execute:
                id: on_preset_set
                preset_mode: ${quiet_preset_name}
                fan_speed: ${quiet_preset_speed}
      - if:
          condition:
            lambda: return x == "${low_preset_name}";
          then:
            - script.execute:
                id: on_preset_set
                preset_mode: ${low_preset_name}
                fan_speed: ${low_preset_speed}
      - if:
          condition:
            lambda: return x == "${medium_preset_name}";
          then:
            - script.execute:
                id: on_preset_set
                preset_mode: ${medium_preset_name}
                fan_speed: ${medium_preset_speed}
      - if:
          condition:
            lambda: return x == "${high_preset_name}";
          then:
            - script.execute:
                id: on_preset_set
                preset_mode: ${high_preset_name}
                fan_speed: ${high_preset_speed}

# script:
#   - id: ${id}_on_preset_set
#     parameters: 
#       preset_mode: string
#       fan_speed: int
#     then:
#       - logger.log:
#           format: Preset mode %s found, setting fan speed to %d
#           args:
#             - preset_mode.c_str()
#             - fan_speed
#           level: DEBUG
#           tag: ${id}
#       - fan.turn_on:
#           id: ${id}
#           speed: !lambda return fan_speed;