name: Build and Publish ESPHome firmware and website

on:
  push:
    branches:
      - main

jobs:
  germination-chamber:
    name: Publish Germination Chamber
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: germination-chamber-esp8266.yaml
      # CHANGEME: Set the name of your project here:
      name: Germination Chamber
      clean: false
      manifest_filename: germination-chamber-manifest.json
  project-template:
    name: Publish Project Template
    uses: esphome/workflows/.github/workflows/publish.yml@dependabot/github_actions/esphome/build-action-3.1.0
    with:
      # CHANGEME: Set the filenames of your config files here:
      files: project-template-esp32.yaml,project-template-esp8266.yaml
      # CHANGEME: Set the name of your project here:
      name: Project Template
      clean: false
      manifest_filename: project-template-manifest.json
